name: CI
on: [push, workflow_call, workflow_dispatch]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          check-latest: true
          node-version: lts/jod

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint
