name: CI
on: [push, workflow_call, workflow_dispatch]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          check-latest: true
          node-version: lts/jod

      - name: Install Dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps --only-shell

      - name: Lint
        run: npm run lint

      - name: Run type checks
        run: npx tsc -p tsconfig.json --noEmit

      - name: Run Playwright tests
        run: npx playwright test